 source("\\\\helix.klient.uib.no\\biohome\\aey022\\rdata\\Mabira vegetation survey data\\matrix veg load data.r")


# ESM of env vars by age class - should it be spots and se's if I use anovas?
#change env to have the right names in newage
levels(env$newage) <- c("og", "ms", "ys")

library(multcomp)

for(i in c(3,5,18,10,8,9,6,7,11,12,13,20)){
lmi<-lm(env[,i]~newage, data=env)
if(anova(lmi)[5][[1]][1]<0.05){
print(paste(colnames(env[i]),anova(lmi)[4][[1]][1],anova(lmi)[5][[1]][1]))
print(TukeyHSD(anova(lmi)))
}} #have checked and NAs seem to be neatly ignored here (I made an NA free subset just to be sure). Sigs are BA**, deadwood **, pH **, N***, C**, TCat***

for(i in c(3,5,18,10,8,9,6,7,11,12,13,20)){

aovi<-aov(env[,i]~newage, data=env)
if(summary(aovi)[[1]][5][[1]][1]<0.05){
print(paste(colnames(env[i]),summary(aovi)[[1]][4][[1]][1],summary(aovi)[[1]][5][[1]][1]))
print(TukeyHSD(aovi))
}}




glht(lmtest, mcp(env="Tukey"))

summary(fm1 <- aov(breaks ~ wool + tension, data = warpbreaks))
TukeyHSD(fm1, "tension", ordered = TRUE)


env$fixLLCov<-exp(env$LLCov) #CAREFUL!!!!!
means<-aggregate(env[!is.na(env$TCat),c(3,5,18,10,22,9,6,7,11,12,13,20)], by=list(env$newage[!is.na(env$TCat)]), FUN=mean)# the c list for columns looks odd to make a "pretty" order. Refer to the object 'axesy' to find the order expected 
means<-means[2:13]
sds<-aggregate(env[!is.na(env$TCat),c(3,5,18,10,22,9,6,7,11,12,13,20)], by=list(env$newage[!is.na(env$TCat)]), FUN=sd)
counts<-table(env$newage)
ses<-sds[2:13]/sqrt(counts) 
axesy<-c("Slope (degrees from horizontal)", "Basal area**", "Canopy open %","Shrub cover %","Leaf litter cover (%)", "Leaf litter depth (cm)",  "Items of deadwood**", "Stumps per plot" , "Soil pH**", "Soil carbon (g/100g)**", "Soil nitrogen (g/100g)***" , "Total soil cations (milliequivalents)***")
ymaxes<-ceiling(apply((means+ses),2,max))

library(Hmisc)
par(mar=c(2.5,3,0.5,1),oma=c(5,0,0,0), mfrow=c(3,4), mgp=c(2,0.4,0), tcl=-0.4, xpd=NA)
 
for(i in 1:12) {
  errbar(c(2.8, 2, 1.2),means[,i], (means[,i]+ses[,i]), (means[,i]-ses[,i]), xlim=c(1,3),  xaxt="n", xlab="", ylab=axesy[i], ylim=c(0,(ymaxes[i]+(ymaxes[i]/10)))) 
axis(1, at=c(2.8, 2, 1.2), labels=(c("OG","MS","YS")))
}    ##i tells the loop which element of the object to look at, so here it tells the loop that on the fifth iteration it needs to take the fifth element (ie column) of the object 'means'. The data are switched in position to make ys come first to match the paper.

#unfortunately, the beautiful loop is messed up by the need to insert text in each figure 
text(-5.0,2675,"a") #BA
text(-4.2,2680,"ab")
text(-3.4,2680,"b")
text(-1.9,1700,"a") #deadwood
text(-1.1,1700,"a")
text(-0.3,1705,"b")
text(-8.1,710,"a") #ph
text(-7.28,715,"b")
text(-6.5,715,"ab")
text(-5.0,710,"a") #C
text(-4.2,715,"b")
text(-3.4,715,"b")
text(-1.9,710,"a") #N
text(-1.1,715,"b")
text(-0.3,715,"b")
text(1.2,710,"a") #TCat
text(2,715,"b")
text(2.8,715,"b")


mtext("ESM 2. Mean values (± 1 standard error) for the measured environmental variables in different forest types. " , side = 1, line = 1, outer =TRUE, cex=0.7)
mtext( "YS - younger secondary, MS - mid secondary, OG - older growth. Where differences were found to be significant" , side = 1, line = 2, outer =TRUE, cex=0.7)
mtext("within ANOVA, y-axis labels indicate this: ** represents significance at the 0.01 and *** at the 0.001 level. " , side = 1, line = 3, outer =TRUE, cex=0.7)
mtext("Letters on the figure represent subgroups generated by Tukey HSD post-hoc tests. " , side = 1, line = 4, outer =TRUE, cex=0.7)

savePlot("Eycott et al ESM env vars spot.eps", type="eps")
savePlot("Eycott et al ESM env vars spot.pdf", type="pdf")




pdf("fuckit.pdf")
par(mar=c(3,3,0,1),oma=c(0,0,0,0), mfrow=c(3,4), mgp=c(2,0.4,0), tcl=-0.4)
#topo - not dist from stream because that was structured into design
boxplot(Slope~newage, data=env, ylab="Slope (degrees from horizontal)")
#structure
boxplot(BA~newage, data=env, ylab="Basal area") 
boxplot(LLCover~newage, data=env, ylab="Leaf litter cover (%)", ylim=c(0,5)) 
boxplot(LLDepth~newage, data=env, ylab="Leaf litter depth (cm)", ylim=c(0,2.5))
boxplot(ShrubCover~newage, data=env, ylab="Shrub cover %", ylim=c(0,60)) 
boxplot(Deadwood~newage, data=env, ylab="Items of deadwood") 
boxplot(Stumps~newage, data=env, ylab="Stumps per plot") 
boxplot(CanO~newage, data=env, ylab="Canopy open %") 
#soil
boxplot(pH~newage, data=env, ylab="Soil pH")
boxplot(C.~newage, data=env, ylab="Soil carbon (g/100g)")
boxplot(N.~newage, data=env, ylab="Soil nitrogen (g/100g)", ylim=c(0,1))
boxplot(TCat~newage, data=env, ylab="Total soil cations (milliequivalents)")
savePlot("Eycott et al ESM env vars box.eps", type="eps")
savePlot("Eycott et al ESM env vars box.pdf", type="pdf")

lmBA<-lm(BA~newage, data=env)
plot(lmBA)#looks good
anova(lmBA)#**
anova(lmBA,type='II',white.adjust='hc3')#not working, but parked the code here. Might need car library

lmLLC<-lm(LLCover~newage, data=env)
plot(lmLLC)#looks ok
anova(lmLLC)#ns

 
boxplot(LLDepth~newage, data=env, ylab="Leaf litter depth(cm)", ylim=c(0,2.5))
boxplot(ShrubCover~newage, data=env, ylab="Shrub cover %", ylim=c(0,60)) 
boxplot(Deadwood~newage, data=env, ylab="Items of deadwood") 
boxplot(Stumps~newage, data=env, ylab="Stumps per plot") 
boxplot(CanO~newage, data=env, ylab="Canopy open %") 
#soil
boxplot(pH~newage, data=env, ylab="Soil pH")
boxplot(C.~newage, data=env, ylab="Soil carbon (UNITS???)")
boxplot(N.~newage, data=env, ylab="Soil nitrogen (UNITS???)", ylim=c(0,1))
boxplot(TCat~newage, data=env, ylab="Total soil cations (milliequivalents)") 

plot(env$LLCover~env$Slope)
cor.test(env$LLCover,env$Slope, method="spearman")


rowSums(aggregate(subcanopywoody[!is.na(subcanopywoody[1]),], by = list(env$newage[!is.na(subcanopywoody[1])]), FUN = "sd")[,-1])

rowSums(aggregate(subcanopywoody[!is.na(subcanopywoody[1]),], by = list(env$newage[!is.na(subcanopywoody[1])]), FUN = "mean")[,-1])
                        