keep5<-!is.na(trees[,1])&rowSums(trees)>0&!is.na(env[,1])
keep6<-!is.na(subcanopywoody[,1])&rowSums(subcanopywoody)>0&!is.na(env[,1])
keep2<-!is.na(trueherbs[,1])&rowSums(trueherbs)>0&!is.na(env[,1])
keep3<-!is.na(ferns[,1])&rowSums(ferns)>0&!is.na(env[,1])

temp<-merge(trees[keep5,],env$newage, by="row.names") 
bigtreesYS<-temp[temp$y=="ys",2:51]
bigtreesYS<-t(bigtreesYS)
YSstep1<-merge(ang_hab,bigtreesYS, by.x="Species_Name", by.y="row.names", all=FALSE)
str(YSstep1)
YSstep1$total<-rowSums(YSstep1[,5:15]>0) 
YSsums<-xtabs(total~Habitat, data=YSstep1)

bigtreesOS<-temp[temp$y=="os",2:51]
bigtreesOS<-t(bigtreesOS)
OSstep1<-merge(ang_hab,bigtreesOS, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(OSstep1)
OSstep1$total<-rowSums(OSstep1[,5:18]>0) 
OSsums<-xtabs(total~Habitat, data=OSstep1)
bigtreesOG<-temp[temp$y=="og",2:51]
bigtreesOG<-t(bigtreesOG)
OGstep1<-merge(ang_hab,bigtreesOG, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(OGstep1)
OGstep1$total<-rowSums(OGstep1[,5:8]>0) 
OGsums<-xtabs(total~Habitat, data=OGstep1)
Tsums<-cbind(YSsums/sum(YSsums), OSsums/sum(OSsums), OGsums/sum(OGsums))
colnames(Tsums)<-c("YS","OS","OG")

temp<-merge(subcanopywoody[keep6,],env$newage, by="row.names") 
temp
str(temp)
subcanopywoodyYS<-temp[temp$y=="ys",2:83]
subcanopywoodyYS<-t(subcanopywoodyYS)
YSstep1<-merge(ang_hab,subcanopywoodyYS, by.x="Species_Name", by.y="row.names", all=FALSE)
str(YSstep1)
YSstep1$total<-rowSums(YSstep1[,5:18]>0) 
YSsums<-xtabs(total~Habitat, data=YSstep1)
subcanopywoodyOS<-temp[temp$y=="os",2:83]
subcanopywoodyOS<-t(subcanopywoodyOS)
OSstep1<-merge(ang_hab,subcanopywoodyOS, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(OSstep1)
OSstep1$total<-rowSums(OSstep1[,5:17]>0) 
OSsums<-xtabs(total~Habitat, data=OSstep1)
subcanopywoodyOG<-temp[temp$y=="og",2:83]
subcanopywoodyOG<-t(subcanopywoodyOG)
OGstep1<-merge(ang_hab,subcanopywoodyOG, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(OGstep1)
OGstep1$total<-rowSums(OGstep1[,5:8]>0) 
OGsums<-xtabs(total~Habitat, data=OGstep1)
Ssums<-cbind(YSsums/sum(YSsums), OSsums/sum(OSsums), OGsums/sum(OGsums))
colnames(Ssums)<-c("YS","OS","OG")

temp<-merge(trueherbs[keep2,],env$newage, by="row.names") 
str(temp)
trueherbYS<-temp[temp$y=="ys",2:32]
trueherbYS<-t(trueherbYS)
YSstep1<-merge(ang_hab,trueherbYS, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(YSstep1)
YSstep1$total<-rowSums(YSstep1[,5:18]>0) 
YSsums<-xtabs(total~Habitat, data=YSstep1)
trueherbOS<-temp[temp$y=="os",2:32]
trueherbOS<-t(trueherbOS)
OSstep1<-merge(ang_hab,trueherbOS, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(OSstep1)
OSstep1$total<-rowSums(OSstep1[,5:17]>0) 
OSsums<-xtabs(total~Habitat, data=OSstep1)
trueherbOG<-temp[temp$y=="og",2:32]
trueherbOG<-t(trueherbOG)
OGstep1<-merge(ang_hab,trueherbOG, by.x="Species_Name", by.y="row.names", all=FALSE)
dim(OGstep1)
OGstep1$total<-rowSums(OGstep1[,5:8]>0) 
OGsums<-xtabs(total~Habitat, data=OGstep1)
Hsums<-cbind(YSsums/sum(YSsums), OSsums/sum(OSsums), OGsums/sum(OGsums))
colnames(Hsums)<-c("YS","OS","OG")

temp<-merge(ferns[keep3,],env$newage, by="row.names") 
fernsYS<-temp[temp$y=="ys",2:30]
fernsYS<-t(fernsYS)
YSstep1<-merge(fern_hab,fernsYS, by.x=0, by.y=0, all=FALSE)
str(YSstep1)
YSstep1$total<-rowSums(YSstep1[,5:19]>0) 
YSsums<-xtabs(total~Habitat, data=YSstep1)
fernsOS<-temp[temp$y=="os",2:30]
fernsOS<-t(fernsOS)
OSstep1<-merge(fern_hab,fernsOS, by.x=0, by.y=0, all=FALSE)
dim(OSstep1)
OSstep1$total<-rowSums(OSstep1[,5:33]>0) 
OSsums<-xtabs(total~Habitat, data=OSstep1)
fernsOG<-temp[temp$y=="og",2:30]
fernsOG<-t(fernsOG)
OGstep1<-merge(fern_hab,fernsOG, by.x=0, by.y=0, all=FALSE)
dim(OGstep1)
OGstep1$total<-rowSums(OGstep1[,5:14]>0) 
OGsums<-xtabs(total~Habitat, data=OGstep1)
Fsums<-cbind(YSsums/sum(YSsums), OSsums/sum(OSsums), OGsums/sum(OGsums))
colnames(Fsums)<-c("YS","OS","OG")

coloury=c("grey 35","grey65","white")
x11();par(mfrow=c(2,3), mar=c(4,3,1,1), mgp=c(2,0.8,0), cex.main=1, pin=c(1.5,2), xpd=NA) 
barplot(Tsums, ylim=c(0,1), xlab="Age class", ylab="Proportion of occurrences", col=coloury, xaxt="n")
title(main="Trees > 10 cm dbh", line=2, font.main=1)
text(0.7, -0.04, "Younger", cex=0.9)
text(0.7, -0.1, "secondary", cex=0.9)
text(2, -0.04, "Mid-", cex=0.9)
text(2, -0.1, "secondary", cex=0.9)
text(3.1, -0.04, "Older", cex=0.9)
text(3.1, -0.1, "growth", cex=0.9)
barplot(Ssums, ylim=c(0,1), xlab="Age class", ylab="Proportion of occurrences", col=coloury, xaxt="n")
title(main="Shrubs and saplings < 10 cm dbh", line=2, font.main=1)
text(0.7, -0.04, "Younger", cex=0.9)
text(0.7, -0.1, "secondary", cex=0.9)
text(2, -0.04, "Mid-", cex=0.9)
text(2, -0.1, "secondary", cex=0.9)
text(3.1, -0.04, "Older", cex=0.9)
text(3.1, -0.1, "growth", cex=0.9)
plot(Ssums,type="n", axes=F, xlab="",ylab="")
legend("topleft",legend=c("Open habitat affiliation", "Forest specialist", "Forest generalist"), fill=c("white","grey65","grey35"))
barplot(Hsums, ylim=c(0,1), xlab="Age class", ylab="Proportion of occurrences",  col=coloury, xaxt="n")
title(main="Herbs", line=2, font.main=1)
text(0.7, -0.04, "Younger", cex=0.9)
text(0.7, -0.1, "secondary", cex=0.9)
text(2, -0.04, "Mid-", cex=0.9)
text(2, -0.1, "secondary", cex=0.9)
text(3.1, -0.04, "Older", cex=0.9)
text(3.1, -0.1, "growth", cex=0.9)
barplot(Fsums, ylim=c(0,1), xlab="Age class", ylab="Proportion of occurrences", col=coloury, xaxt="n")
title(main="Ferns", line=2, font.main=1)
text(0.7, -0.04, "Younger", cex=0.9)
text(0.7, -0.1, "secondary", cex=0.9)
text(2, -0.04, "Mid-", cex=0.9)
text(2, -0.1, "secondary", cex=0.9)
text(3.1, -0.04, "Older", cex=0.9)
text(3.1, -0.1, "growth", cex=0.9)
savePlot("Fig 3 All affiliations.emf", type="emf")
savePlot("Fig 3 All affiliations.eps", type="eps")