library(vegan)
library(RODBC)
##file.choose()
afram<-odbcConnectAccess2007("C:\\stat\\Aframomum\\Biomass_performance\\Biomass_3_17_04_2015.accdb")
Env<-odbcConnectAccess2007("C:\\stat\\Aframomum\\Biomass_performance\\Biomass_3_17_04_2015.accdb")
variable<-sqlQuery(afram,"select * from performance1")
#compart<-sqlQuery(research,"select * from Compartment")
variable2<-sqlQuery(Loc,"select * from EnvVariables")

x11(width=5,height=9);par(mfrow=c(4,2),mar=c(2,1,2,0.5),mgp=c(1,.3,0),oma=c(0,2,0,0),cex=.7,tcl=.25,xpd=T,las=1.55)
#fortype<-xtabs(AvgOfStemLength~LocationType,Location2)
boxplot(AvgOfpH~LocationType,variable2,main="Soil PH")
boxplot(AvgOfcarbon~LocationType,variable2,main="Soil carbon")
boxplot(AvgOfNitrogen~LocationType,variable2,main="Nitrogen")
boxplot(AvgOfCalcium~LocationType,variable2,main="calcium")
boxplot(AvgOfpotassium~LocationType,variable2,main="Potassium")
boxplot(AvgOfsodium~LocationType,variable2,main="Sodium")
boxplot(AvgOfcover~LocationType,variable2,main="Cover")
