#Here are the spotplots in three for transect sums only

library(Hmisc)

x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot(sums$spprich~sums$Distance, ylab="Total number species", ylim=c(0,40), xlim=c(0,15), col= c("gray27", "red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Distance from forest (km)")
errbar(sums$Distance, sums$spprich, maxes$spprich, mins$spprich, add=T, type="n")
plot(sums$spprich~sums$FragmentSize, ylab="Total number species", ylim=c(0,40), xlim=c(0,500), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Fragment size (ha)")
errbar(sums$FragmentSize, sums$spprich, maxes$spprich, mins$spprich, add=T, type="n")
plot(sums$spprich~sums$V1.y, ylab="Total number species", ylim=c(0,40), xlim=c(0,25), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
errbar(sums$V1.y, sums$spprich, maxes$spprich, mins$spprich, add=T, type="n")
legend(x=38, y=40,c("Bushland fragments","Farmland fragments","Sugarcane fragments", "Continuous Forest"),pch=16, col=c("gray27","gray57","gray87","red"))
savePlot("poster threespotplots ordinary richness.eps", type="eps")

x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot(sums$rarefied~sums$Distance, ylab="Rarefied species richness", ylim=c(0,45), xlim=c(0,15), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Distance from forest (km)")
errbar(sums$Distance, sums$rarefied, maxes$rarefied, mins$rarefied, add=T, type="n")
plot(sums$rarefied~sums$FragmentSize, ylab="Rarefied species richness", ylim=c(0,45), xlim=c(0,500), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Fragment size (ha)")
errbar(sums$FragmentSize, sums$rarefied, maxes$rarefied, mins$rarefied, add=T, type="n")
plot(sums$rarefied~sums$V1.y, ylab="Rarefied species richness", ylim=c(0,45), xlim=c(0,25), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
errbar(sums$V1.y, sums$rarefied, maxes$rarefied, mins$rarefied, add=T, type="n")
legend(x=38, y=40,c("Bushland fragments","Farmland fragments","Sugarcane fragments", "Continuous Forest"),pch=16, col=c("gray27","gray57","gray87","red"))
savePlot("poster threespotplots rarefied richness.eps", type="eps")

x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot(sums$abun~sums$Distance, ylab="Bird abundance", ylim=c(0,300), xlim=c(0,15), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Distance from forest (km)")
errbar(sums$Distance, sums$abun, maxes$totalbirds, mins$totalbirds, add=T, type="n")
plot(sums$abun~sums$FragmentSize, ylab="Bird abundance", ylim=c(0,300), xlim=c(0,500), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Fragment size (ha)")
errbar(sums$FragmentSize, sums$abun, maxes$totalbirds, mins$totalbirds, add=T, type="n")
plot(sums$abun~sums$V1.y, ylab="Bird abundance", ylim=c(0,300), xlim=c(0,25), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
errbar(sums$V1.y, sums$abun, maxes$totalbirds, mins$totalbirds, add=T, type="n")
legend(x=38, y=250,c("Bushland fragments","Farmland fragments","Sugarcane fragments", "Continuous Forest"),pch=16, col=c("gray27","gray57","gray87","red"))
savePlot("poster threespotplots abundance.eps", type="eps")

x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot(sums$HShann~sums$Distance, ylab="Diversity (Shannon H)", ylim=c(1.5,3.5), xlim=c(0,15), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xlab="Distance from forest (km)")
errbar(sums$Distance, sums$HShann, maxes$y, mins$y, add=T, type="n")
plot(sums$HShann~sums$FragmentSize, ylab="Diversity (Shannon H)", ylim=c(1.5,3.5), xlim=c(0,500), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=F, xlab="Fragment size (ha)")
errbar(sums$FragmentSize, sums$HShann, maxes$y, mins$y, add=T, type="n")
plot(sums$HShann~sums$V1.y, ylab="Diversity (Shannon H)", ylim=c(1.5,3.5), xlim=c(0,25), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
errbar(sums$V1.y, sums$HShann, maxes$y, mins$y, add=T, type="n")
legend(x=38, y=3.5,c("Bushland fragments","Farmland fragments","Sugarcane fragments", "Continuous Forest"),pch=16, col=c("gray27","gray57","gray87","red"))
savePlot("poster threespotplots HShann.eps", type="eps")


x11(); par(mar=c(5,4,2,1), mfrow=c(2,2), xpd=NA)
plot((sums$FF/sums$totalbirds)~sums$Distance, ylab="Proportion of forest specialists (FF)", ylim=c(0,1), xlim=c(0,15), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Distance from forest (km)")
errbar(sums$Distance,(sums$FF/sums$totalbirds) , maxes$FFprop, mins$FFprop, add=T, type="n")
plot((sums$FF/sums$totalbirds)~sums$FragmentSize, ylab="Proportion of forest specialists (FF)", ylim=c(0,1), xlim=c(0,500), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=F, xlab="Fragment size (ha)")
errbar(sums$FragmentSize,(sums$FF/sums$totalbirds) , maxes$FFprop, mins$FFprop, add=T, type="n")
plot((sums$FF/sums$totalbirds)~sums$V1.y, ylab="Proportion of forest specialists (FF)", ylim=c(0,1), xlim=c(0,25), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
errbar(sums$V1.y,(sums$FF/sums$totalbirds) , maxes$FFprop, mins$FFprop, add=T, type="n")
legend(x=38, y=0.9,c("Bushland fragments","Farmland fragments","Sugarcane fragments", "Continuous Forest"),pch=16, col=c("gray27","gray57","gray87","red"))
savePlot("poster threespotplots FFprop.eps", type="eps")

x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot((sums$INGR/sums$totalbirds)~sums$Distance, ylab="Proportion of ground insectivores", ylim=c(0,0.4), xlim=c(0,15), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xlab="Distance from forest (km)")
errbar(sums$Distance,(sums$INGR/sums$totalbirds) , maxes$INGRprop, mins$INGRprop, add=T, type="n")
plot((sums$INGR/sums$totalbirds)~sums$FragmentSize, ylab="Proportion of ground insectivores", ylim=c(0,0.4), xlim=c(0,500), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=F, xlab="Fragment size (ha)")
errbar(sums$FragmentSize,(sums$INGR/sums$totalbirds) , maxes$INGRprop, mins$INGRprop, add=T, type="n")
plot((sums$INGR/sums$totalbirds)~sums$V1.y, ylab="Proportion of ground insectivores", ylim=c(0,0.4), xlim=c(0,25), col= c("gray27","red","gray57","gray87")[as.factor(sums$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
errbar(sums$V1.y,(sums$INGR/sums$totalbirds) , maxes$INGRprop, mins$INGRprop, add=T, type="n")
legend(x=38, y=0.4,c("Bushland fragments","Farmland fragments","Sugarcane fragments", "Continuous Forest"),pch=16, col=c("gray27","gray57","gray87","red"))
savePlot("poster threespotplots INGRprop.eps", type="eps")

#gleaning insectivores: most species NOT FIXED YET
x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot((total$INGLL/total$totalbirds)~total$Distance, ylab="Proportion of gleaning insectivores", ylim=c(0,0.4), xlim=c(0,15), col= c("gray27","gray57","gray87", "gray7")[as.factor(total$Matrix.type)],pch=16, cex=1.5, xlab="Distance from forest (km)")
points(sums$Distance,(sums$INGLL/sums$totalbirds), pch=21, bg= c("gray27","gray7","gray57", "gray87")[as.factor(sums$Matrix.type)],cex=1.5)
plot((total$INGLL/total$totalbirds)~total$FragmentSize, ylab="Proportion of gleaning insectivores", ylim=c(0,0.4), xlim=c(0,500), col= c("gray27","gray57","gray87", "gray7")[as.factor(total$Matrix.type)],pch=16, cex=1.5, xpd=F, xlab="Fragment size (ha)")
points(sums$FragmentSize,(sums$INGLL/sums$totalbirds), pch=21, bg= c("gray27","gray7","gray57", "gray87")[as.factor(sums$Matrix.type)],cex=1.5)
plot((total$INGLL/total$totalbirds)~total$CanopyOpeness, ylab="Proportion of gleaning insectivores", ylim=c(0,0.4), xlim=c(0,40), col= c("gray27","gray57","gray87", "gray7")[as.factor(total$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
points(sums$V1.y,(sums$INGLL/sums$totalbirds), pch=21, bg= c("gray27","gray7","gray57", "gray87")[as.factor(sums$Matrix.type)],cex=1.5)
legend(x=60, y=0.4,c("Bushland overall value","Bushland transects","Farmland overall value","Farmland transects","Sugarcane overall value","Sugarcane transects", "Continuous Forest overall value", "Continuous Forest transects"),pch=21, pt.bg=c("gray27","gray27","gray57","gray57","gray87","gray87","gray7","gray7"), col=c("black", "NA")) 
savePlot("three spotplots INGLL proportion square.emf")

#frugivores - most tested by other people
x11(); par(mar=c(5,4,1,1), mfrow=c(2,2), xpd=NA)
plot(((total$FR+total$FRIN)/total$totalbirds)~total$Distance, ylab="Proportion of frugivores", ylim=c(0,0.6), xlim=c(0,15), col= c("gray27","gray57","gray87", "gray7")[as.factor(total$Matrix.type)],pch=16, cex=1.5, xlab="Distance from forest (km)")
points(sums$Distance,(sums$FRFRIN/sums$totalbirds), pch=21, bg= c("gray27","gray7","gray57", "gray87")[as.factor(sums$Matrix.type)],cex=1.5)
plot(((total$FR+total$FRIN)/total$totalbirds)~total$FragmentSize, ylab="Proportion of frugivores", ylim=c(0,0.6), xlim=c(0,500), col= c("gray27","gray57","gray87", "gray7")[as.factor(total$Matrix.type)],pch=16, cex=1.5, xpd=F, xlab="Fragment size (ha)")
points(sums$FragmentSize,(sums$FRFRIN/sums$totalbirds), pch=21, bg= c("gray27","gray7","gray57", "gray87")[as.factor(sums$Matrix.type)],cex=1.5)
plot(((total$FR+total$FRIN)/total$totalbirds)~total$CanopyOpeness, ylab="Proportion of frugivores", ylim=c(0,0.6), xlim=c(0,40), col= c("gray27","gray57","gray87", "gray7")[as.factor(total$Matrix.type)],pch=16, cex=1.5, xpd=NA, xlab="Canopy Openness (%)")
points(sums$V1.y,(sums$FRFRIN/sums$totalbirds), pch=21, bg= c("gray27","gray7","gray57", "gray87")[as.factor(sums$Matrix.type)],cex=1.5)
legend(x=59, y=0.4,c("Bushland overall value","Bushland transects","Farmland overall value","Farmland transects","Sugarcane overall value","Sugarcane transects", "Continuous Forest overall value", "Continuous Forest transects"),pch=21, pt.bg=c("gray27","gray27","gray57","gray57","gray87","gray87","gray7","gray7"), col=c("black", "NA")) 
savePlot("three spotplots FRFRIN proportion square.emf")
